// Package mypackage provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package mypackage

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// NotesV1Error defines model for notes.v1.Error.
type NotesV1Error struct {
	Code    *int32  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NotesV1Note defines model for notes.v1.Note.
type NotesV1Note struct {
	Author    *string `json:"author,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	Private   *bool   `json:"private,omitempty"`
	Text      *string `json:"text,omitempty"`
	Timestamp *string `json:"timestamp,omitempty"`
}

// NotesV1NoteFilter defines model for notes.v1.NoteFilter.
type NotesV1NoteFilter struct {
	After   *string   `json:"after,omitempty"`
	Author  *[]string `json:"author,omitempty"`
	Before  *string   `json:"before,omitempty"`
	Ids     *[]int64  `json:"ids,omitempty"`
	Private *bool     `json:"private,omitempty"`
}

// NotesV1Notebook defines model for notes.v1.Notebook.
type NotesV1Notebook struct {
	Error *NotesV1Error  `json:"error,omitempty"`
	Notes *[]NotesV1Note `json:"notes,omitempty"`
}

// NotesV1NoteServiceCreateJSONBody defines parameters for NotesV1NoteServiceCreate.
type NotesV1NoteServiceCreateJSONBody = NotesV1Note

// NotesV1NoteServiceFetchJSONBody defines parameters for NotesV1NoteServiceFetch.
type NotesV1NoteServiceFetchJSONBody = NotesV1NoteFilter

// NotesV1NoteServiceCreateJSONRequestBody defines body for NotesV1NoteServiceCreate for application/json ContentType.
type NotesV1NoteServiceCreateJSONRequestBody = NotesV1NoteServiceCreateJSONBody

// NotesV1NoteServiceFetchJSONRequestBody defines body for NotesV1NoteServiceFetch for application/json ContentType.
type NotesV1NoteServiceFetchJSONRequestBody = NotesV1NoteServiceFetchJSONBody
